version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Entering Spring Boot project directory"
      - cd AirBnBApp
      - mvn clean package -Dmaven.test.skip=true -Dspring.profiles.active=dev

artifacts:
  files:
    - AirBnBApp/target/*.jar
  discard-paths: yes