spring.application.name=AirBnBApp

# DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/AirBnB
spring.datasource.username=postgres
spring.datasource.password=Shashi12@2Gupta

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true